mpi:
  # incompatibility with Meson: https://github.com/mesonbuild/meson/issues/7045
  # - mpich    # [not win]
  - openmpi  # [not win]
  # TODO: we could try that later, see mpi4py-feedstock
  # - impi     # [not osx and x86_64]
  # - msmpi    # [win]
