{% set name = "fluidfft-mpi_with_fftw" %}
{% set version = "0.0.1" %}
{% set mpi = mpi or 'mpich' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fluidfft_mpi_with_fftw-{{ version }}.tar.gz
  sha256: ab8c1867e745715892f8d30c9409e9509467a610f5a702ac7b5cfa003787f6ce

build:
  number: 0
  skip: true  # [py<39 or win]
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv'

requirements:
  build:
    - {{ compiler('cxx') }}
    # as in https://github.com/conda-forge/mpi4py-feedstock
    - python                                 # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ mpi }}                              # [build_platform != target_platform and mpi == "openmpi"]
  host:
    - pkg-config
    - python
    - meson-python
    - numpy
    - fluidfft-builder >=0.0.1
    - cython
    - transonic >=0.6.1
    - pip
    - fftw
    - {{ mpi }}
    - mpi4py
  run:
    - python
    - fluidfft
    - fftw
    - {{ mpi }}
    - mpi4py

test:
  imports:
    - fluidfft_mpi_with_fftw
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Fluidfft plugin for parallel FFTs using fftw
  license: GPL-3.0-or-later
  license_file: LICENSE
  home: https://foss.heptapod.net/fluiddyn/fluidfft

extra:
  recipe-maintainers:
    - paugier
